# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dpmfa.validators.validator
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Compartment')),
                ('description', models.TextField(verbose_name='description of this model')),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('evt_changed', models.DateTimeField(auto_now=True, verbose_name='Time of last change')),
                ('log_inflows', models.BooleanField(default=True, verbose_name='Log inflows')),
                ('categories', models.CharField(max_length=250, validators=[dpmfa.validators.validator.alpha_numeric_list_validator], verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='compartment_inflow_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(null=True, verbose_name='Run')),
                ('period', models.IntegerField(null=True, verbose_name='Period')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='compartment_inventory_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(null=True, verbose_name='Run')),
                ('period', models.IntegerField(null=True, verbose_name='Period')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='external_inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('start_delay', models.SmallIntegerField(verbose_name='Start delay')),
                ('derivation_distribution', models.CharField(max_length=250, verbose_name='Probability density function')),
                ('derivation_parameters', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message=None)], verbose_name='Parameter list of the probability distribution function')),
                ('derivation_factor', models.FloatField(verbose_name='Derivation factor')),
            ],
        ),
        migrations.CreateModel(
            name='flow_compartment_outflow_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(null=True, verbose_name='Run')),
                ('period', models.IntegerField(null=True, verbose_name='Period')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='local_release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='local release', max_length=250, verbose_name='Local release')),
                ('delay', models.SmallIntegerField(null=True, verbose_name='Delay')),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('seed', models.FloatField(verbose_name='Seed')),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('evt_changed', models.DateTimeField(auto_now=True, verbose_name='Time of last change')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(verbose_name='Runs')),
                ('periods', models.IntegerField(verbose_name='Periods')),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('evt_changed', models.DateTimeField(auto_now=True, verbose_name='Time of last change')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='dpmfa.model', verbose_name='model')),
            ],
        ),
        migrations.CreateModel(
            name='single_period_inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.BigIntegerField(verbose_name='current inflow value')),
                ('period', models.IntegerField(verbose_name='Period')),
            ],
        ),
        migrations.CreateModel(
            name='stock_immediate_flow_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(null=True, verbose_name='Run')),
                ('period', models.IntegerField(null=True, verbose_name='Period')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('priority', models.SmallIntegerField(verbose_name='Priority')),
                ('current_tc', models.FloatField(verbose_name='Current transfer coefficient')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='aggregated_transfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.transfer')),
            ],
            bases=('dpmfa.transfer',),
        ),
        migrations.CreateModel(
            name='constant_transfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.transfer')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
            bases=('dpmfa.transfer',),
        ),
        migrations.CreateModel(
            name='external_function_inflow',
            fields=[
                ('external_inflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.external_inflow')),
                ('inflow_function', models.CharField(max_length=250, verbose_name='Inflow function')),
            ],
            bases=('dpmfa.external_inflow',),
        ),
        migrations.CreateModel(
            name='external_list_inflow',
            fields=[
                ('external_inflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.external_inflow')),
            ],
            bases=('dpmfa.external_inflow',),
        ),
        migrations.CreateModel(
            name='fixed_rate_release',
            fields=[
                ('local_release_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.local_release')),
                ('release_rate', models.FloatField(null=True, verbose_name='Release rate')),
            ],
            bases=('dpmfa.local_release',),
        ),
        migrations.CreateModel(
            name='fixed_value_inflow',
            fields=[
                ('single_period_inflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.single_period_inflow')),
                ('value', models.FloatField(verbose_name='the inflow value')),
            ],
            bases=('dpmfa.single_period_inflow',),
        ),
        migrations.CreateModel(
            name='flow_compartment',
            fields=[
                ('compartment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.compartment')),
                ('adjust_outgoing_tcs', models.BooleanField(default=True, verbose_name='Adjust outgoing TCs')),
                ('log_outflows', models.BooleanField(default=True, verbose_name='Log outflows')),
            ],
            bases=('dpmfa.compartment',),
        ),
        migrations.CreateModel(
            name='function_release',
            fields=[
                ('local_release_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.local_release')),
                ('release_function', models.CharField(max_length=250, verbose_name='Release function')),
            ],
            bases=('dpmfa.local_release',),
        ),
        migrations.CreateModel(
            name='list_release',
            fields=[
                ('local_release_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.local_release')),
                ('release_rate_list', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message=None)], verbose_name='Release rate list')),
            ],
            bases=('dpmfa.local_release',),
        ),
        migrations.CreateModel(
            name='random_choice_inflow',
            fields=[
                ('single_period_inflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.single_period_inflow')),
                ('sample', models.CharField(max_length=250, verbose_name='Sample')),
            ],
            bases=('dpmfa.single_period_inflow',),
        ),
        migrations.CreateModel(
            name='random_choice_transfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.transfer')),
                ('sample', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message=None)], verbose_name='Sample')),
            ],
            bases=('dpmfa.transfer',),
        ),
        migrations.CreateModel(
            name='stochastic_inflow',
            fields=[
                ('single_period_inflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.single_period_inflow')),
                ('pdf', models.CharField(max_length=250, verbose_name='Pdf')),
                ('parameter_values', models.CharField(max_length=250, verbose_name='Pdf parameter values')),
            ],
            bases=('dpmfa.single_period_inflow',),
        ),
        migrations.CreateModel(
            name='stochastic_transfer',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.transfer')),
                ('parameters', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message=None)], verbose_name='Parameters')),
                ('function', models.CharField(max_length=250, verbose_name='Function')),
            ],
            bases=('dpmfa.transfer',),
        ),
        migrations.AddField(
            model_name='transfer',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='dpmfa.compartment'),
        ),
        migrations.AddField(
            model_name='model',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dpmfa.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='external_inflow',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_inflows', to='dpmfa.compartment'),
        ),
        migrations.AddField(
            model_name='compartment_inventory_record',
            name='compartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartment_inventory_records', to='dpmfa.compartment', verbose_name='Compartment'),
        ),
        migrations.AddField(
            model_name='compartment_inflow_record',
            name='compartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartment_inflow_records', to='dpmfa.compartment', verbose_name='Compartment'),
        ),
        migrations.AddField(
            model_name='compartment',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='dpmfa.model'),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('flow_compartment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dpmfa.flow_compartment')),
                ('local_release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='dpmfa.local_release')),
            ],
            bases=('dpmfa.flow_compartment',),
        ),
        migrations.AddField(
            model_name='transfer',
            name='belongs_to_aggregated_transfer',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='dpmfa.aggregated_transfer', verbose_name='Aggregated transfer'),
        ),
        migrations.AddField(
            model_name='single_period_inflow',
            name='external_list_inflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_period_inflows', to='dpmfa.external_list_inflow', verbose_name='External list inflow'),
        ),
        migrations.AddField(
            model_name='flow_compartment_outflow_record',
            name='flow_compartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_compartment_outflow_records', to='dpmfa.flow_compartment', verbose_name='Flow compartment'),
        ),
        migrations.AddField(
            model_name='external_function_inflow',
            name='basic_inflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpmfa.single_period_inflow', verbose_name='name of the single period inflow'),
        ),
        migrations.AddField(
            model_name='stock_immediate_flow_record',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_immediate_flow_records', to='dpmfa.stock', verbose_name='Stock'),
        ),
    ]
