# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpmfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
    ]
