# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpmfa', '0002_model_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartment',
            old_name='created_date',
            new_name='evt_created',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='created_date',
            new_name='evt_created',
        ),
    ]
