# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpmfa', '0004_auto_20170730_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(verbose_name='description of this model'),
        ),
    ]
